services:
    backend:
        build:
            context: backend/.
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/splittery
        depends_on:
            - db
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: splittery
    frontend:
        build:
            context: frontend/.
            dockerfile: Dockerfile
        environment:
            - API_URL=http://172.17.0.1:8080/api
        ports:
            - "3000:3000"
