apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
    namespace: splittery
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            initContainers:
                - name: wait-for-postgres
                  image: busybox
                  command:
                      [
                          "sh",
                          "-c",
                          "until nc -z database-service 5432; do echo waiting for postgres; sleep 2; done;",
                      ]
            containers:
                - name: splittery-backend
                  image: philippderroole/splittery-backend:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8000
                  env:
                      - name: DATABASE_URL
                        valueFrom:
                            secretKeyRef:
                                name: database-secrets
                                key: url
