---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: splittery
spec:
  encryptedData:
    jwt_secret: AgCNf21Z6h3aGY67S3Bq08iFaKZZ9JbMtLGxyUM2jJOXIR4VScSo1SWFR9fZ5sfCdxjMcRRcu5Jv+HGZ5cUgT9psqWKG8SYRI0UxRQL8VxKQ7sUC2A/k0YhBSI0CMJl4DaDpVHDW6olTd3pri7TlYH81heDt81niT1ZOD6lbMzIXL9J1gZe6YryoOZK0bYfRoWCLaJZDN5V9e+iiZpZfhsOTXEOsb+DHmoPwx6b/H8Egu5YSjTYF+ssWqlB7zR/swrknNUzQvW95L5JzLkvyUmerkhtCfSjc4xpdD4fCL71FexJkN3RIJhwFsVZuv676qatRbEo/zxwZKvH7QgitygvMsfyhEaKJjiMT31UQOFYrrbxh34I2VFBeVKjPVqGurYYj1rqO3AKtMmwewPD/s/hul3I0IX9G9nSl9HEuhrTvGL/kwhP2Lr78p/JelLlrNgvbL7gPwD2mGVd6Or1v9PHJ7ilJ6k/iWdcRF7p00kGh3a321rQmWBkd/Cs3S3I5SEm4RSl8wGa+HI8vU+DKUdZ+l6/CVAB+C2Gz/yoMZwv/96KDRNRGeiemfeKnYWm9V9pZSZLlT8kXwJvXtG/84GTLfVFesgVUdwpC5uCP/Crc0Skfn04jZw5XW7S9lqEKFpWCWCi0UtXNMkn55yxcMKvdNp9aYqQE3KO1hUhzpCKaww/gata441eb2angWL6nLi25Yl4Ltzh/BnrEKsB0WxoZjT3b/FrMj9EL6SmL7nsEgw==
  template:
    metadata:
      name: backend-secrets
      namespace: splittery
