---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-secrets
  namespace: splittery
spec:
  encryptedData:
    password: AgCe/7vzWxTmw1o8vQ0y1HzMVQAps28U+TCgtrj0Rpc17iNKDS5f49VKXYprheWGd5BB3Tt4vyDiGZr4Ef0L5wUXhzrj+P1+Txb6cBC7Be3VsJdTzgrCtzLBH6uuNT/iMOWpEptqh5EGbR1qkpZ3n+EmERPff2MU4kFQJeU3k78690fDNS5rxacq6TZDFI8A2Gf7bePgb8gi3HIgsbEGZ/XvxPM6HI13XYPMdnUP68RjdU/bpil4IjfMH6LSMjf2sFpH0hq0H6AtrUN0REaZqeBbiOr0dHLixx9GWdZ8FatToPkDJft2nxm4UFG2FKv/pxFZWIb2HL0XJO9dN6DxowTD3HrneqgS/ftm2JCyYPPGa+r1sQtmdmDMoFjK1hgrXh4IfnopH45hszk9d4NWhenKaTfh40V0u+c/RLaXvQmISs9pSzon91CgTir8nYTFnF1/WNKhgSh0FhHXx5nJ4eaaMxWd3XkV0u/IwblBNtpflg1zJmx+BLDzzgb6V7AP8/07HwGemCQm19Oy0rb8N6Wnrh0GTqPe+QkpOHhZxik7gKmo4WmLqxzNc6573OFTbIx9TDLlCHBQAwy88MYGoqGLMERVT+pm0lscqq8TFdKoWd8zt2MvQSDEUC/OpVPE5tQQdFF4vSAKczoEFbLqz4flAuAkim5tLqAqthYeb8oJGZuvM5ocxJS7ZyZpaEnxiObynF1zJEa4y3EXllmYaDE4wta+r3QzTjUyub+VPtsfhQdgdhbE3Mhs77uxlZe0ER1Eud8uZ7Z4ZZK5qd/EvdxLaL4jxDQcQ7wYa/4J3O1QpW5AAlw+2v2mk5CZUK1vv/DSMU9L
    url: AgAXq2Nt9cn8JHJLlnRBBNqvaGnijg4GVlFPLT6eruHMPQh5vthxiNUbG2e7pkLrTTpbikIxVX2hK0j1S+q9ZWdzjkxIaKEw66PMKdrxrtKJWu0/fcgiubThcgFlHAF/rHLlQKvlNrjXKjpBnqxbBImJZyLXcf4Kfu9UYwxzQf56MI1rr/kjN8fR/BbRWy53nEaAhkAgO8ieJ0oPpDK68cgGBtPQtN9y7pl+canqLx4BsZiyK8Xrq8WVuVyQCKq9X91fetBv7zTBVF4YBwoNGTACjT9qL7Hzv8+ei/RLUFqDLTNF7i4NGTEm4buvLVaY6j6DDjT+TD05FnPTG04K0+dpGNlZtggg3QMeYsNBKywda/IkG2f/nc+CXcCxz0YXQH50AcshdlC2yMa2FBkRd5Z87L2iEpU5LZvzjucOLzQRDflPQbeIlKLF6Eh3Vg6T+//lMdMmu4o3NmKbnfDdtHaIaELVcR7A1nhM5QvDQNrqvmqegVWfDv2zeVBe6e8HdBciiUa4V54RN4+TOEaWgakd0jyUGJkK2DvBaEdIgKBzis5j4DNHADZSdddsAMTtEwN6pNGtfkgbsCay2NxIb+23PL2xIIzL4VAE8ITsU3I+563TPAm0FUKBkMPjzpEYXG+QGBCBR9JqqmWtv+aKyTHjYX8NznFMqD763ir+W9sMj6eu/1BEDxZ3dRsBKXvcNKK+x7ZHw+vbEDGrC6o+DvR6Ockbn1wgMMyBwRfwy1GTsEHj0rh+hYSs0kydlS4ajIzgA7lQIk+34OVgf7r8NwJPdpNt6veEJcqu5JnV7IWicioEl0EVIs9U9/WYln4Ixqv0clEvH/DAmIiJH/apEJ6Jj1iN/iqN/wNRHxrERxwQR9K/8EMlLiS//9I4R2USxZSVzRAZ2ThMwgOm
  template:
    metadata:
      creationTimestamp: null
      name: database-secrets
      namespace: splittery
    type: Opaque
