apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: powersync
type: Opaque
stringData:
    PS_DATA_SOURCE_URI: postgres://postgres:mypassword@pg-db:5432/postgres
    PS_MONGO_URI: mongodb://mongo:27017/powersync_demo
    PS_PORT: "8080"
    PS_JWKS_URL: http://demo-backend:6060/api/auth/keys
