name: Build frontend Docker image

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    REGISTRY: docker.io
    IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/splittery-frontend

jobs:
    build:
        name: Build and push Docker image
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: ./frontend
                  file: ./frontend/Dockerfile
                  platforms: linux/amd64
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  build-args: |
                      BUILDKIT_INLINE_CACHE=1

            - name: Image digest
              if: github.event_name != 'pull_request'
              run: echo ${{ steps.build.outputs.digest }}
